add_executable(sub0mempage-probe-options-tests probe_options_tests.cpp)
target_link_libraries(sub0mempage-probe-options-tests PRIVATE Sub0MemPage::Sub0MemPage)
target_include_directories(sub0mempage-probe-options-tests PRIVATE "${PROJECT_SOURCE_DIR}/tools/intel")
if(MSVC)
    target_compile_options(sub0mempage-probe-options-tests PRIVATE /W4 /WX)
else()
    target_compile_options(sub0mempage-probe-options-tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
endif()
add_test(NAME sub0mempage.probe-options COMMAND sub0mempage-probe-options-tests)
