execute_process(COMMAND "${PROBE}" --help RESULT_VARIABLE code OUTPUT_VARIABLE output)
if(NOT code STREQUAL "0" OR NOT output MATCHES "Usage:")
    message(FATAL_ERROR "Help failed: ${code}: ${output}")
endif()
foreach(arg IN ITEMS --unknown --device-id=xyz --device-id= --device-id=100000000 --device-id=-1)
    execute_process(COMMAND "${PROBE}" "${arg}" RESULT_VARIABLE code ERROR_VARIABLE error)
    if(NOT code STREQUAL "2" OR NOT error MATCHES "argument_error=")
        message(FATAL_ERROR "Expected argument rejection for ${arg}, got ${code}: ${error}")
    endif()
endforeach()
